[package]
name = "codegen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0"
serde-generate = "0.25"
serde-reflection = "0.3"
data_types = {path = "../data_types"}
