// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Protocol

import "strconv"

type CommandUnion byte

const (
	CommandUnionNONE     CommandUnion = 0
	CommandUnionResponse CommandUnion = 1
	CommandUnionRedirect CommandUnion = 2
	CommandUnionShutdown CommandUnion = 3
)

var EnumNamesCommandUnion = map[CommandUnion]string{
	CommandUnionNONE:     "NONE",
	CommandUnionResponse: "Response",
	CommandUnionRedirect: "Redirect",
	CommandUnionShutdown: "Shutdown",
}

var EnumValuesCommandUnion = map[string]CommandUnion{
	"NONE":     CommandUnionNONE,
	"Response": CommandUnionResponse,
	"Redirect": CommandUnionRedirect,
	"Shutdown": CommandUnionShutdown,
}

func (v CommandUnion) String() string {
	if s, ok := EnumNamesCommandUnion[v]; ok {
		return s
	}
	return "CommandUnion(" + strconv.FormatInt(int64(v), 10) + ")"
}
