// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Protocol

import "strconv"

type InfoUnion byte

const (
	InfoUnionNONE    InfoUnion = 0
	InfoUnionPacket  InfoUnion = 1
	InfoUnionLogLine InfoUnion = 2
)

var EnumNamesInfoUnion = map[InfoUnion]string{
	InfoUnionNONE:    "NONE",
	InfoUnionPacket:  "Packet",
	InfoUnionLogLine: "LogLine",
}

var EnumValuesInfoUnion = map[string]InfoUnion{
	"NONE":    InfoUnionNONE,
	"Packet":  InfoUnionPacket,
	"LogLine": InfoUnionLogLine,
}

func (v InfoUnion) String() string {
	if s, ok := EnumNamesInfoUnion[v]; ok {
		return s
	}
	return "InfoUnion(" + strconv.FormatInt(int64(v), 10) + ")"
}
