// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type LogLine struct {
	_tab flatbuffers.Table
}

func GetRootAsLogLine(buf []byte, offset flatbuffers.UOffsetT) *LogLine {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &LogLine{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsLogLine(buf []byte, offset flatbuffers.UOffsetT) *LogLine {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &LogLine{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *LogLine) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *LogLine) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *LogLine) Line() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func LogLineStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func LogLineAddLine(builder *flatbuffers.Builder, line flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(line), 0)
}
func LogLineEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
