// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Protocol

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Shutdown struct {
	_tab flatbuffers.Table
}

func GetRootAsShutdown(buf []byte, offset flatbuffers.UOffsetT) *Shutdown {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Shutdown{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsShutdown(buf []byte, offset flatbuffers.UOffsetT) *Shutdown {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Shutdown{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *Shutdown) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Shutdown) Table() flatbuffers.Table {
	return rcv._tab
}

func ShutdownStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func ShutdownEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
